### ISSUE TITLE
Does not work on Rails 3.1

### ISSUE THREAD

**Issue by ChaosSteffen** [grosser/translation_db_engine#1]
/Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in `const_missing': uninitialized constant ActionDispatch::Routing::Routes (NameError)
    from /Users/steffen/repo/dawanda-cms/vendor/plugins/translation_db_engine/config/routes.rb:4
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/routes_reloader.rb:29:in`load_paths'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/routes_reloader.rb:29:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/routes_reloader.rb:29:in`load_paths'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/routes_reloader.rb:13:in `reload!'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/routes_reloader.rb:7:in`initialize'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-3.1.0/lib/active_support/file_update_checker.rb:32:in `call'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-3.1.0/lib/active_support/file_update_checker.rb:32:in`execute_if_updated'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/finisher.rb:63
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/finisher.rb:64:in `call'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application/finisher.rb:64
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/initializable.rb:25:in`instance_exec'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `run'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/initializable.rb:50:in`run_initializers'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `each'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/initializable.rb:49:in`run_initializers'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/application.rb:92:in `initialize!'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in`send'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from ./spec/../config/environment.rb:5
    from /Users/steffen/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /Users/steffen/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from ./spec/spec_helper.rb:2
    from /Users/steffen/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /Users/steffen/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Users/steffen/repo/dawanda-cms/spec/helpers/application_helper_spec.rb:1
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/configuration.rb:419:in`load'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/configuration.rb:419:in `load_spec_files'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/configuration.rb:419:in`map'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/configuration.rb:419:in `load_spec_files'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/command_line.rb:18:in`run'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/runner.rb:80:in `run_in_process'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/runner.rb:69:in`run'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/gems/rspec-core-2.6.3/lib/rspec/core/runner.rb:11:in `autorun'
    from /Users/steffen/.rvm/gems/ruby-1.8.7-p302/bin/rspec:19

**Comment by grosser** [comment]
fixed

**Comment by ChaosSteffen** [comment]
I like!
