### ISSUE TITLE
weird helper overriding code in controllers

### ISSUE THREAD

**Issue by costa** [grosser/translation_db_engine#3]
Would you care to tell which scenario the code at app/controllers/translation_keys_controller.rb:9 is supposed to protect against?
And why the controller does not inherit from ApplicationController?
Thanks.

**Comment by grosser** [comment]
it should not blow up when you are using it in a layout that uses current_user / logged_in?, it's kind of silly but was all I needed to get it running in our original project.

it seems to be the general trend to inherit from applicationcontroller, so could you go ahead and remove these stub methods and make it inherit from it ?

**Comment by costa** [comment]
yes, that's what i did, just wanted to check if there was anything more to it. thanks.

**Comment by grosser** [comment]
how about a pull request ? :)

**Comment by costa** [comment]
oh noes, sorry, i did just a quick local fix just like you said, it's no good for general usage which will require more substantial refactoring

**Comment by grosser** [comment]
just pushed those changes, please have a look if it is helpful to you / if you made more then these

**Comment by costa** [comment]
yes, this pretty much does it, thank you very much
